#设置熔断器
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            #超时时间，默认1000ms
            #注意：这里的时间大小取决于ribbon的ReadTimeout，ConnectTimeout，超时重试次数，重试负载均衡次数。
            #计算公式：(1+MaxAutoRetriesNextServer+(1+MaxAutoRetriesNextServer)*MaxAutoRetries)*(ReadTimeout+ConnectTimeout)，
            #考虑网络因素，计算结果最好再加1
            timeoutInMilliseconds: 11000
      circuitBreaker:
        #熔断器开启的阀值，具体指在最近统计时间(默认10s)内请求的次数(默认20次)。也就是10秒内至少请求20次，才触发熔断器机制
        requestVolumeThreshold: 10 #做测试使用，这里改为10次
        #熔断器工作时间(默认5s)，即：5秒内熔断器会中断前端请求，执行回调方法，5秒后会关闭重试(状态由OPEN切换到HELF OPEN),
        #如果请求成功，则关闭熔断器(状态由HELF OPEN切换到CLOSE);
        #如果请求仍然失败,继续打开熔断器5秒(状态由HELF OPEN切换到OPEN),如此循环。
        sleepWindowInMilliseconds: 5000
        #当出错率超过50%(默认50)，启动熔断器
        errorThresholdPercentage: 50
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 2000
  okToRetryOnAllOperation: false
  MaxAutoRetries: 0
  maxAutoRetiesNextServer: 1

upload:
  pic:
    path: c:/uploadfiles/dev
